language: cpp

matrix:
  include:
    - env: GCC_VERSION=5 CPP=11 LIBCXX=Off
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

before_install: 
- git submodule update --init --recursive
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install python-yaml libyaml-dev build-essential libssh2-1-dev libarchive-dev
- sudo apt-get install libgsl0-dev libsqlite3-dev

script: 
- ./configure && make apophenia && make && make install

branches: 
  only: 
  - master
